---
services:
  freqtrade-spot:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-spot
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_spot.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_spot.sqlite
      --config /freqtrade/user_data/config_spot.json
      --strategy SampleStrategy

  freqtrade-perps:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-perps
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8082"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_perps.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_perps.sqlite
      --config /freqtrade/user_data/config_perps.json
      --strategy SampleStrategy
